### ISSUE TITLE
Homebrew install not working

### ISSUE THREAD

**Issue by chrowe** [acquia/club#8]
Looks like the PR has not been merged yet https://github.com/Homebrew/homebrew-php/pull/3749

**Comment by kylebrowning** [comment]
Correct. WE seem to be getting some flak too.

**Comment by kylebrowning** [comment]
@chrowe 

Okay so for now, should be able to run `brew install kylebrowning/acquia/club`

Ill work on getting this moved on to the official Acquia repo after I talk to some colleagues about it.

Let me know if this doesn't work!

**Comment by kylebrowning** [comment]
@chrowe THis is fixed,

brew install acquia/tools/club

**Comment by koppieesq** [comment]
2 years later, it's broken again:
```$ brew tap acquia/tools
==> Tapping acquia/tools
Cloning into '/usr/local/Homebrew/Library/Taps/acquia/homebrew-tools'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 6 (delta 0), reused 4 (delta 0), pack-reused 0
Unpacking objects: 100% (6/6), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/acquia/homebrew-tools/Formula/club.rb
club: cannot load such file -- /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Abstract/abstract-php-phar.rb
Error: Cannot tap acquia/tools: invalid syntax in tap!
```
Can we reopen this issue?  Or should I create a new one?
