### ISSUE TITLE
Box dependency

### ISSUE THREAD

**Issue by chrowe** [acquia/club#9]
There seems to be a dependency on https://github.com/box-project/box2 (at least using the Manual git checkout install process).

I used `brew install box` to get that but the project recommends a curl based install.

Not sure how this should be handled.

**Comment by kylebrowning** [comment]
Hrmm. yes. I think running `composer require --dev kherge/box` would resolve this so it comes with `composer install`

**Comment by kylebrowning** [comment]
But then the command you need is `./vendor/box/box`

**Comment by kylebrowning** [comment]
This is fixed in #10
